# Generated by Django 5.2.3 on 2025-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookintegration',
            name='webhook_url',
            field=models.URLField(max_length=500),
        ),
    ]
