services:
  - type: web
    name: zentry-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn zentry_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://zentry-ron-cada-projects.vercel.app/"
  
  - type: pserv
    name: zentry-postgres
    env: postgres
    region: oregon

databases:
  - name: zentry-db
    databaseName: zentry
    user: zentry_user
