# Generated by Django 5.2.3 on 2025-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='🏆', max_length=10)),
                ('badge_type', models.CharField(choices=[('streak', 'Streak'), ('tasks', 'Tasks'), ('level', 'Level'), ('special', 'Special')], default='tasks', max_length=20)),
                ('requirement_value', models.IntegerField(help_text="Number needed to unlock (e.g., 5 for '5-day streak')")),
                ('experience_reward', models.IntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('tasks_completed', 'Tasks Completed'), ('experience_points', 'Experience Points'), ('current_streak', 'Current Streak'), ('longest_streak', 'Longest Streak')], max_length=30)),
                ('value', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
